version: "3.8"

services:
  frontend:
    build: ./frontend/client
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/client:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend/server
    ports:
      - "4000:4000"
    volumes:
      - ./backend/server:/app
      - /app/node_modules
