version: "3.8"

services:
  frontend:
    build: ./frontend/client
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/client:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend/server
    ports:
      - "4000:4000"
    volumes:
      - ./backend/server:/app
      - /app/node_modules
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/bancodedados
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
